name: Build and push

on:
  push:
    branches: [ master ]
    tags: [ "*" ]

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Make
      run: make

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Make push
      if: github.ref == 'refs/heads/master'
      run: make push

    - name: Make push latest
      if: startsWith(github.ref, 'refs/tags/')
      run: make push-latest
